### ISSUE TITLE
 create parameter to save the contents of the input without the mask

### ISSUE THREAD

**Issue by osmanfilho** [amarkes/br-mask#1]
add content saving functionality without the mask

**Comment by amarkes** [comment]
whats?

**Comment by thelebdev** [comment]
No seriously, what? @osmanfilho

**Comment by diogomiloco** [comment]
I believe he means to allow a way to keep the mask only on the template and store the raw value on the variable.

Example:
Template: 123.123.123.12 (CPF mask) 
varlable: 12312312312

**Comment by amarkes** [comment]
use replace man!
