### ISSUE TITLE
Using br-mask without form

### ISSUE THREAD

**Issue by blondie63** [amarkes/br-mask#11]
Oi, Is it possible to use br-mask without form ?
Like v1.6.3 for Ionic 3:
`<input type="text" name="cpf" placeholder="CPF" [brmasker]="{mask:'000.000.000-00', len:14}" value="">`

**Comment by amarkes** [comment]
a versão 3 possibilitava de fazer um write sem precisar passar o form, porem da conflito na versão 4, por isso é obrigatório usa-lo.

**Comment by blondie63** [comment]
OK mais nao entendo se eu posso usar sem uma form..
simple ion-input
