### ISSUE TITLE
Using [brmasker] not working

### ISSUE THREAD

**Issue by jean-poiski** [amarkes/br-mask#12]
"Can't bind to 'brmasker' since it isn't a known property of 'ion-input'"

Quando utilizo o componente conforme os exemplos, apresenta essa mensagem de erro.
O uso do FormControl é obrigatório? Tem algo a mais que devesse ser feito após a instalação?

**Comment by amarkes** [comment]
neste caso ele alega que não foi importado o [brmasker](https://github.com/amarkes/br-mask#usage)
deve esta importando de forma errada!

**Comment by jean-poiski** [comment]
Tipo isso? Já está no projeto...
![image](https://user-images.githubusercontent.com/37163029/53963635-701d8680-40cc-11e9-8111-9cf56fe0b6d2.png)

**Comment by amarkes** [comment]
depende da arquitetura! Se for modular não...

**Comment by jean-poiski** [comment]
Desculpe minha ignorância, mas não entendi...
É um aplicativo, tanto no browser como no dispositivo dão a mesma mensagem de erro e não funciona.
