### ISSUE TITLE
Exemplo Ionic 4

### ISSUE THREAD

**Issue by AdemilsonMarsiglio** [amarkes/br-mask#2]
Olá, gostaria que pudesse criar alguns exemplos básicos de uso.
Para quem está iniciando em ionic, é complicado...

Vi que para o ionic 3 tem exemplo, mas é diferente...

Fico no Aguardo.

**Comment by amarkes** [comment]
ja existe um exemplo

**Comment by AdemilsonMarsiglio** [comment]
O exemplo que vc diz é o que está no Readme? pois para mim deu erros. Deve ter algum tratamento especial?

**Comment by amarkes** [comment]
quais são os erros?

**Comment by AdemilsonMarsiglio** [comment]
> quais são os erros?

De noite eu descrevo aqui, com certeza fiz algo errado.

Eu fiz isso:

```
import { BrMaskerModule } from 'br-mask';

@NgModule({
  imports: [
    BrMaskerModule
  ],
})
```



Mas este código acima, coloquei no .module da pagina que tem esta funcionalidade, não no app.module.

E no HTML usei este exemplo: https://github.com/amarkes/br-mask#example-for-real-99999-with-decimal

Porém dá uma monte de erro  no navegador.. 

A noite eu descrevo bem o erro.

**Comment by AdemilsonMarsiglio** [comment]
Olha só, o problema era meu mesmo, mas aonde eu estava errando:

- Eu queria que o input mascarasse uma propriedade da minha classe (por exemplo: item.preco).
  - Mas o que eu tive que fazer: criar um FormGroup e adicionar este campo ao form group.
  - O que eu não gostei, foi que não ficou mais automatico o binding. Tive que adicionar evento (ionChange) para alterar o valor do atributo.

Não tem uma forma de mascarar uma propriedade da minha classe? por exemplo, no HTML eu usaria [(ngModel)]="item.preco".
