### ISSUE TITLE
Improve Money mask

### ISSUE THREAD

**Issue by eulerchavez** [amarkes/br-mask#22]
Hi there, thanks for the project!

Working with it, I realice money mask is limited by certain characters, see the follow image

![image](https://user-images.githubusercontent.com/18647380/60908029-8a18d280-a240-11e9-968a-3d3803cc1f35.png)

We could improve this with the follow Regex

![image](https://user-images.githubusercontent.com/18647380/60908143-c8ae8d00-a240-11e9-8823-c77dd92eb86b.png)
`
'100000000000000000000'.replace(/\B(?=(\d{3})+(?!\d))/g, ',')`

I hope this can be use in future.

**Comment by amarkes** [comment]
ok, quer consertar?
