### ISSUE TITLE
Propriedade para remover "bind" da máscara no FormControlName

### ISSUE THREAD

**Issue by llinq** [amarkes/br-mask#3]
Olá, seria possível criar uma propriedade para desabilitar a máscara no valor do FormControlName ?

Eu possuo um campo de CPF que é necessário ser apresentado com máscara para o usuário porém deve ser validado sem máscara, é claro que consigo remover a máscara facilmente com regex, porém seria possível fazer isso através de uma configuração passada no Input brmasker ? Obrigado :)

(Me desculpe pela Issue em pt-br).

**Comment by llinq** [comment]
duplicates from https://github.com/amarkes/br-mask/issues/1 ?

**Comment by amarkes** [comment]
usa replace para validação
