### ISSUE TITLE
form control valueChanges does not fire after implement directive

### ISSUE THREAD

**Issue by ThonyFD** [amarkes/br-mask#4]
hi all, great job!

I'm having an issue after implement the directive [brmasker] in a reactive form input. The event value changes does not fire anymore.

this.form.get('inputName').valueChanges

any idea  what it's goin on?

**Comment by amarkes** [comment]
something is doing wrong because it does not affect the property `valueChanges`

**Comment by ThonyFD** [comment]
I  was replace all your Reactive Form references to native element and it's working
