### ISSUE TITLE
ERROR: Uncaught (in promise): TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by damtaipu** [amarkes/br-mask#43]
I have the following error after installing and running Ionic serves:

core.js:6185 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'id' of undefined

What can it be?

My configuration:
`Ionic:

   Ionic CLI                     : 6.3.0 (C:\Users\DilDam\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.900.7
   @angular-devkit/schematics    : 9.0.7
   @angular/cli                  : 9.0.7
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\DilDam\AppData\Local\Android\Sdk)
   NodeJS            : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.3
   OS                : Windows 10`

**Comment by damtaipu** [comment]
Complete Error:

`core.js:6185 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'id' of undefined
TypeError: Cannot read property 'id' of undefined
    at registerNgModuleType (core.js:35929)
    at core.js:35947
    at Array.forEach (<anonymous>)
    at registerNgModuleType (core.js:35943)
    at new NgModuleFactory$1 (core.js:36105)
    at Compiler_compileModuleSync__POST_R3__ (core.js:40687)
    at Compiler_compileModuleAsync__POST_R3__ [as compileModuleAsync] (core.js:40700)
    at MergeMapSubscriber.project (router.js:6455)
    at MergeMapSubscriber._tryNext (mergeMap.js:46)
    at MergeMapSubscriber._next (mergeMap.js:36)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41264)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)`

**Comment by lucasrleandro** [comment]
Same problem. Did u fix it?

**Comment by faheemfactor** [comment]
Remove 'NgModule' import in any modules. This will remove the above error.
That might require the router link on controls to replace with some click.

It took me 3 hours. Though eventually, backtracking found the cause due to 'NgModule' import. 
I hope that helps. 👍 

The ionic Team needs to work better on showing errors.

**Comment by damtaipu** [comment]
> Same problem. Did u fix it?

https://github.com/amarkes/br-mask/issues/43#issuecomment-747109798

**Comment by damtaipu** [comment]
> Remove 'NgModule' import in any modules. This will remove the above error.
> That might require the router link on controls to replace with some click.
> 
> It took me 3 hours. Though eventually, backtracking found the cause due to 'NgModule' import.
> I hope that helps. 👍
> 
> The ionic Team needs to work better on showing errors.

Thank you my friend. You really helped me.
