### ISSUE TITLE
Maximum call stack size exceeded on input

### ISSUE THREAD

**Issue by ahrherrera** [amarkes/br-mask#44]
When the user is writting in the input 

CODE:
`<ion-item>
            <ion-label position="stacked">CVC/CVV</ion-label>
            <ion-input formControlName="cvc" class="ion-text-center" inputmode="numeric" type="tel" maxlength="4" [brmasker]="{mask:'0000', len:4, type:'num'}"></ion-input>
          </ion-item>`

![image](https://user-images.githubusercontent.com/15525993/79586430-53ed6680-808e-11ea-9651-c91e7c7fffae.png)

Ionic Info: 
![image](https://user-images.githubusercontent.com/15525993/79586539-7c756080-808e-11ea-9387-a733e07ad48b.png)

**Comment by yuricamara** [comment]
Same here except that it doesn't repeat.

[Edit] I downgraded from version 0.0.9 to 0.0.8 and this problem disappeared.

**Comment by ahrherrera** [comment]
> Same here except that it doesn't repeat.
> 
> [Edit] I downgraded from version 0.0.9 to 0.0.8 and this problem disappeared.

Thank You! It worked.
