### ISSUE TITLE
Mascara Funciona apenas ao receber Foco

### ISSUE THREAD

**Issue by Samuel-Oliveira** [amarkes/br-mask#7]
Tudo bom?
Se eu seto um valor no model, o mesmo só recebe a mascara quando eu foco no input.
Alguma é alguma configuração que não encontrei?

**Comment by amarkes** [comment]
isso resolve? [setServices](https://github.com/amarkes/br-mask/blob/master/README.md#features)

**Comment by Samuel-Oliveira** [comment]
Sim, Tem, interesse em crescer ela?
Fazer prefixo e sufixo, separar o view value e model value?
Posso ajudar caso tenha interesse.

**Comment by amarkes** [comment]
Sempre está aberto a melhorias, desde que atenda a todos os usuários

**Comment by Samuel-Oliveira** [comment]
OK, Vou ver e qualquer coisa lhe aviso!
